left to right direction

[*] --> 在庫中
在庫中 -> [*]

在庫中 --> 貸出中: (蔵書の貸出を登録する)
貸出中 --> 在庫中: (貸出図書の返却を登録する)

state 貸出中 {
  [*] ->  期限内
  期限内 -> 期限切れ: (貸出期限を確認する)

  note right of 期限内: [貸出期限＞＝今日]
  note right of 期限切れ: [貸出期限＜今日]
}
